#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([5.05528123e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.64108274e-066, 1.16188963e+165, 5.28206026e-091,
       1.10618148e-046, 4.34243033e-315])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr = np.full(10 , fill_value = None)
arr[4] = 1
arr

array([None, None, None, None, 1, None, None, None, None, None],
      dtype=object)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.random.randint(10,49,12)
arr

array([18, 28, 12, 11, 27, 22, 46, 31, 15, 26, 25, 27])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(f"The original vector is {arr}")
arr[0] , arr[-1] = arr[-1] , arr[0]
print(f"The reversed vector is {arr}")

The original vector is [1 2 3 4 5 6 7 8]
The reversed vector is [8 2 3 4 5 6 7 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr = np.random.randint(0,8,9).reshape(3,3)
arr

array([[6, 1, 1],
       [0, 4, 5],
       [0, 0, 7]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1,2,0,0,4,0])
np.where(arr == 0)
#np.nonzero(np.array([1,2,0,0,4,0]))

(array([2, 3, 5]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr = np.random.randint(0,27,27).reshape(3,3,3)
arr

array([[[ 5, 18, 13],
        [22, 16,  8],
        [ 8,  0, 20]],

       [[25, 18,  7],
        [13, 13,  1],
        [ 8,  6, 18]],

       [[ 2,  6, 21],
        [ 9, 12, 19],
        [ 0, 19,  2]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.randint(0,111,100).reshape(10,10)
print(f"The 10x10 array is {arr}")
minimum = np.min(arr)
maximum = np.max(arr)
print(f"The minimum value of the array is {minimum}")
print(f"The maximum value of the array is {maximum}")

The 10x10 array is [[ 68  28 102  56  48   7  81  98  91  81]
 [ 64  49   0   6  19 106  72  51  45  53]
 [ 42  76  67  24  82  56   9  58  10  48]
 [ 89  52  16  70  47  48  42  32  89  64]
 [ 11 108  59  94  60  49  78  34   0  22]
 [ 32  37  70  53  57  19  87  89  86  65]
 [ 86  97  54  40  90  98  12  69   5  36]
 [ 38  41  87  68  20  82 103  26  15  39]
 [104 102  38  10  49  74  18  95  87  75]
 [ 34  79  39  11  16  60  51  28  48 107]]
The minimum value of the array is 0
The maximum value of the array is 108


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.randint(0,99,30)
print(f"The vector is {arr}")
mean = np.mean(arr)
print(f"The mean value is {mean}")

The vector is [15 10 45 65 88 67 45 37 38 61 36 85 91 43 62 62 28 69 53 10 47 10 11 46
 28 48 69 65 41  8]
The mean value is 46.1


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.zeros(9).reshape(3,3)

arr[0:3 , 0] = 1
arr[0:3 , 2] = 1
arr[0:3:2 , 1:2] = 1

print(arr)

#a = np.ones((10,10))
#a[1:-1,1:-1]=0
#a

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.ones(25).reshape(5,5)
arr = np.pad(arr,1)
arr

#a = np.ones((5,5))
#a = np.pad(a,2)
#a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)   # 0
print(np.nan == np.nan) # True
print(np.inf > np.nan)  # True
print(np.nan - np.nan)  # 0
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1) # True

nan
False
False
nan
True
False
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr = np.random.randint(0,25,25).reshape(5,5)
arr = np.diag(np.arange(1,5))
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr = np.zeros((8,8))
arr[::2 , ::2 ] = 1
arr[1::2 , 1::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile?

In [ ]:
arr = np.array([[0,1],[1,0]])
checkboard = np.tile(arr,(4,4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr = np.random.rand(5,5)
mean = np.mean(arr)
standard_deviation = np.std(arr)
Z = mean / standard_deviation

print(f"The original array is {arr}")
print(f"The normalization factor is {Z}")


The original array is [[0.44159285 0.32432655 0.84654062 0.44126551 0.81046261]
 [0.35763998 0.9542319  0.13816562 0.69078884 0.47872361]
 [0.8163857  0.64362589 0.367015   0.07769262 0.97540999]
 [0.54722486 0.43669437 0.44083901 0.05509656 0.61338375]
 [0.84632577 0.61239244 0.43015658 0.10999907 0.41514912]]
The normalization factor is 1.9725336310242985


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

<ipython-input-76-4daa7c2f2b60>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.random.rand(5,3)
matrix2 = np.random.rand(3,2)

print(np.dot(matrix1,matrix2))

[[0.91676187 1.59209716]
 [0.47830529 0.80154517]
 [0.74674981 1.46290494]
 [0.81962409 1.06809331]
 [1.12049922 1.2958251 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(11)
arr[4:8] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
S = sum(range(5))
print(S)
print("First line without importing NumPy --> ",S-1)
print()
print("Second line with NumPy --> ",sum(range(5),-1))

10
First line without importing NumPy -->  9

Second line with NumPy -->  10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([0,1,2,3,4])
# z**z ---> Legal
# 2 << Z >> 2 ---> Legal
# Z <- Z ---> Legal
# 1j*Z ---> Legal
# Z/1/1 ---> Legal
# Z<Z>Z ---> Not Legal
z

array([0, 1, 2, 3, 4])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0) # ---> nan
np.array(0) // np.array(0) # ---> 0
np.array([np.nan]).astype(int).astype(float) # ---> nan

<ipython-input-104-e0b0e65d5078>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) # ---> nan
<ipython-input-104-e0b0e65d5078>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # ---> 0


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [2]:
arr = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[ 5.  8.  9. -3.  2. -1. -8.  8. -9. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
matrix1 = np.array([1,2,3,5,7,11])
matrix2 = np.array([1,3,5,7,8,11])

print(np.intersect1d(matrix1,matrix2))

[ 1  3  5  7 11]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
print("Done ")

Done 


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
np.datetime_data?
np.datetime64?

In [ ]:
yesterday = np.datetime64('today' , 'D') - np.timedelta64(1 , 'D')
today = np.datetime64('today' , 'D')
tomorrow = np.datetime64('today' , 'D') + np.timedelta64(1 , 'D')

print(f"Yesterday date is {yesterday}")
print(f"Today date is {today}")
print(f"Tomorrow date is {tomorrow}")

Yesterday date is 2023-09-27
Today date is 2023-09-28
Tomorrow date is 2023-09-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
np.add?

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B) # (A+B) stored in B
np.divide(A,2,out=A) # (A/2) stored in A
np.negative(A,out=A) # (A*-1) stored in A
np.multiply(A,B,out=A) # B[A+B] * A[[A+B],[(A*-1)]] ---> computed in place

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.uniform(3,11,10)

print(f"Original array is {arr}")
print()
print(f"floor method: {np.floor(arr)}")
print()
print(f"round method: {np.round(arr)}")
print()
print(f"astype method: {arr.astype(int)}")
print()
print(f"ceil method: {np.ceil(arr)}")

Original array is [ 7.49708048  4.89386107 10.66190012  6.06439654  3.46293924  7.69560064
  9.30599654  7.41423403  5.93312299 10.95256033]

floor method: [ 7.  4. 10.  6.  3.  7.  9.  7.  5. 10.]

round method: [ 7.  5. 11.  6.  3.  8.  9.  7.  6. 11.]

astype method: [ 7  4 10  6  3  7  9  7  5 10]

ceil method: [ 8.  5. 11.  7.  4.  8. 10.  8.  6. 11.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.zeros((5,5))
arr[0:,1] = 1
arr[0:,2] = 2
arr[0:,3] = 3
arr[0:,4] = 4
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
from numpy.core.multiarray import nditer
def generator():
  arr = np.array([])
  for x in range(10):
    arr = np.append(arr,x)
  return arr

matrix = np.array([generator()])
matrix

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.rand(10)
print(f"Original array is {arr}")
print()
arr.sort()
print()
print(f"The sorted array is {arr}")

Original array is [0.47287868 0.78700734 0.28603572 0.36630289 0.17755407 0.24247998
 0.70568975 0.47416093 0.52823672 0.31041091]


The sorted array is [0.17755407 0.24247998 0.28603572 0.31041091 0.36630289 0.47287868
 0.47416093 0.52823672 0.70568975 0.78700734]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.array([1,2,3,4])
sum = np.add.reduce(arr)
sum

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.rand(10)
B = np.random.rand(10)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
A = np.random.rand(10)
A.flags.writeable = False
print(A)
A[1] = 0

[0.42206217 0.63146877 0.20722414 0.06479451 0.26073088 0.18200714
 0.01943023 0.71795213 0.60962258 0.6369418 ]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.82593309 0.25955638 1.09555176 0.35268159 0.55881035 0.07568157
 0.76878182 1.14974591 1.23601063 0.84273862]
[0.10308365 1.09981237 0.75945005 1.55470165 0.7724379  0.97042705
 1.30476442 1.01370739 0.63103529 1.25092163]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = np.random.rand(10)
arr.sort()
print(f"The original vector is: {arr}")
print()
arr[-1] = 0
print(arr)

The original vector is: [0.264262   0.32305671 0.35302469 0.54504546 0.569161   0.67667092
 0.84631084 0.88059461 0.93398746 0.96566003]

[0.264262   0.32305671 0.35302469 0.54504546 0.569161   0.67667092
 0.84631084 0.88059461 0.93398746 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.inf)
arr = np.eye(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
arr = np.arange(100)
print(f"Original array: {arr}")
print()
value = np.random.uniform(0,100)
print(f'The value is: {value}')
print()
index = (np.abs(arr-value)).argmin()
print(arr[index])

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

The value is: 41.08641785884471

41


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
arr = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.10/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import scipy
import scipy.spatial

arr = np.random.random((100,2))
distance = scipy.spatial.distance.cdist(arr,arr)
print(distance)

[[0.         0.29761004 0.37662807 0.70296738 0.75573674 0.29025271
  0.10803055 0.21520128 0.50959825 0.18706285 0.79717204 0.23860054
  0.62976185 0.66691413 0.72883579 0.27076584 0.56209411 0.09594558
  0.65274773 0.48600964 0.48495545 0.32699705 0.18153981 0.51014585
  0.15984137 0.74004064 0.61901953 0.1444157  0.28963769 0.42812697
  0.49609143 0.49254982 0.81032917 0.64400671 0.56459328 0.2389616
  0.43235832 0.58410747 0.45436997 0.43794592 0.74263926 0.36879633
  0.42638692 0.37728739 0.45994388 0.36055931 0.79676115 0.25705651
  0.08716514 0.67276957 0.64843068 0.79664994 0.76346555 0.45618183
  0.35599892 0.35761279 0.32646557 0.60797517 0.35534393 0.44459131
  0.56240958 0.30757308 0.4602604  0.53361311 0.58580547 0.19545684
  0.82691697 0.47688916 0.1457396  0.372152   0.33592732 0.59828129
  0.55558459 0.16646009 0.12663102 0.22910683 0.42550737 0.38546971
  0.34705291 0.4312729  0.79470592 0.25389975 0.13520054 0.6429309
  0.65370713 0.3750209  0.28540769 0.16731124 0.55

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int32)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

file_data = StringIO("""1, 2, 3, 4, 5\n
                        6,  ,  , 7, 8\n
                         ,  , 9,10,11\n""")

read = np.genfromtxt(file_data, delimiter=',', dtype=np.int)
read

<ipython-input-19-cae4b0f84bea>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  read = np.genfromtxt(file_data, delimiter=',', dtype=np.int)


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.arange(12).reshape(3,4)

for index, value in np.ndenumerate(arr):
    print(index, value)

print()
print("===================================================")
print()

for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [3]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [5]:
n = 10
p = 3
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [6]:
arr = np.random.rand(5, 10)
newarr = arr - arr.mean(axis=1).reshape(-1, 1)

print(newarr)

[[ 0.29983445  0.11055293 -0.20531123 -0.06769068 -0.2619028   0.14487264
  -0.09162424 -0.14176287  0.20723435  0.00579747]
 [ 0.03982301  0.42065252  0.06259587 -0.49304538  0.17992779  0.22144731
  -0.34677975  0.10975916 -0.15823633 -0.03614421]
 [ 0.31425988  0.31341864 -0.4756604   0.38489319  0.24061964 -0.5711209
  -0.26923691  0.02250737  0.03719402  0.00312546]
 [-0.02255828 -0.0574975   0.06854055  0.4121472  -0.3288596   0.29003165
  -0.24531831  0.11101861  0.08273726 -0.31024159]
 [ 0.35210872 -0.12030329  0.42350945 -0.2893228  -0.27313674 -0.10793454
  -0.43259962 -0.22201711  0.3920137   0.27768223]]


#### 59. How to sort an array by the nth column? (★★☆)

In [7]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[4 1 5]
 [9 1 2]
 [7 7 2]]
[[4 1 5]
 [9 1 2]
 [7 7 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [9]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)